<?php
$page_name = 'Home Page';
$page_desc = 'Home Page Desc';
$page_keywords = 'Home,Page';

$header_scripts = array();
$footer_scripts = array();

include_once PAGE_DIR.'/common/header.phtml';
include_once PAGE_DIR.'/common/nav.phtml';
?>

<section class="wrapper">
	<div class="inner">
		<h2>404 - Page not Found</h2>
		<p>In arcu accumsan arcu adipiscing accumsan orci ac. Felis id enim aliquet. Accumsan ac integer lobortis commodo ornare aliquet accumsan erat tempus amet porttitor.</p>
	</div>
</section>

<?php
include_once PAGE_DIR.'/common/footer.phtml';
?>