<?php
$page_name = 'Home Page';
$page_desc = 'Home Page Desc';
$page_keywords = 'Home,Page';

$header_scripts = array(
	'<script src="https://cdn.sideai.com/libs/echarts/4.1.0/echarts.min.js"></script>',
);
$footer_scripts = array();

include_once PAGE_DIR.'/common/header.phtml';
include_once PAGE_DIR.'/common/nav.phtml';
?>


<!-- Heading -->
<div id="heading" >
	<h1>Echart Demo</h1>
</div>

<section class="wrapper">
<div class="inner">
<div class="content">
<div id="main1" style="width:100%;height:400px;"></div>
<div id="main2" style="width:100%;height:400px;"></div>
</div>
</div>
</section>

<script type="text/javascript">
	// 基于准备好的dom，初始化echarts实例
	var myChart1 = echarts.init(document.getElementById('main1'));
	var myChart2 = echarts.init(document.getElementById('main2'));

	// 指定图表的配置项和数据
	var option1 = {
		title: {
			text: 'ECharts 入门示例'
		},
		tooltip: {},
		legend: {
			data:['销量']
		},
		xAxis: {
			data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
		},
		yAxis: {},
		series: [{
			name: '销量',
			type: 'bar',
			data: [5, 20, 36, 10, 10, 20]
		}]
	};
	var option2 = {
		title: {
			text: 'ECharts 入门示例'
		},
		tooltip: {},
		legend: {
			data:['销量']
		},
		xAxis: {
			data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
		},
		yAxis: {},
		series: [{
			name: '销量',
			type: 'line',
			data: [5, 20, 36, 10, 10, 20]
		}]
	};

	// 使用刚指定的配置项和数据显示图表。
	myChart1.setOption(option1);
	myChart2.setOption(option2);
</script>

<?php
include_once PAGE_DIR.'/common/footer.phtml';
?>