<body class="is-preload">

<!-- Header -->
<header id="header">
	<a class="logo" href="/">Industrious</a>
	<nav>
		<a href="#menu">Menu</a>
	</nav>
</header>

<!-- Nav -->
<nav id="menu">
	<ul class="links">
		<li><a href="/home">Home</a></li>
		<li><a href="/element">Elements</a></li>
		<li><a href="/generic">Generic</a></li>
		<li><a href="/echart">Echart</a></li>
		<li><a href="/genericdasxsas">404</a></li>
	</ul>
</nav>